services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  meloflavio.notificacao_listener:
    class: MeloFlavio\NotificacaoBundle\Event\EventListener\NotificacaoListener
    tags:
      - name: doctrine.event_subscriber
